### ISSUE TITLE
handleKeyPress в Task7.js

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [rubanykRoman/test-task-onix-react-internship#11]
`finals[0].flag = !finals[0].flag;`
Нежелательно изменять данные из стейта таким образом, проблема в том что значение в обьекте меняется по ссылке из-за чего значение в стейте меняется но это очень не хорошо
из-за этого ты не заметил что ` this.setState({...this.state.finals})` работает не корректно, так как ты обновляешь весь стейт а не поле finals в нем 

так же подобный каскад if'фов можно заменить switch

**Comment by rubanykRoman** [comment]
Переделал. 
Теперь данные из state изменяются только через setState().
Каскад if'фов убрал. Добавил массив с возможными значениями горячих клавиш и прописал более "адаптивную" логику при использовании горячих клавиш.
