### ISSUE TITLE
Работа с DOM в обход реакта

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [rubanykRoman/test-task-onix-react-internship#12]
В `Task7TableRow.js` достаточно много работы с DOM в обход реакта. Так как реакте не знает об этих изменениях в какой-то из перерендеров они могут исчезнуть и это сложно предсказать. Лучше добавь в стейт флажок и в зависимости от него в render накидывай классы

**Comment by rubanykRoman** [comment]
Переделал все зд.
Убрал работу с DOM в обход реакта. Все изменения состояния теперь через setState().
