### ISSUE TITLE
Структура

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [rubanykRoman/test-task-onix-react-internship#13]
Основной послы структуры которую я приводил в пример было избавить от большой вложенности
То есть чтобы не было такого "pages/Home/components/HomeTasks/task9/Users/UsersList.js". Чем больше вложенность тем сложнее ориентироваться по проекте

Вот пара примеров как можно сделать красивее
- папка `layout` в `src` в неё можно вынести `Header` и `Footer`, а так же создать компонент `Layout` который обьедени `Header`, `Footer` и контент страницы
- создать папку `service` в `src` туда можно переместить все запросы которые относятся к пользователям. Так же в `baseUrl` лучше указывать лишь базовый путь, а не полный, то есть лишь `https://607d4f98184368001769d631.mockapi.io`, а остальной путь передавать в самом запросе
- так же в `pages/Home/components` очень не хорошо создавать папки (как писал выше это увеличивает  вложенность)
- ну а `task2`, `task3` ... лучше перенести в `src/components`

**Comment by rubanykRoman** [comment]
Откорректировал структуру, добавил Layout, вынес запросы в service. Добавил роутинг.
