### ISSUE TITLE
Больше компонентов

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [rubanykRoman/test-task-onix-react-internship#14]
В каждом файле `Task*.js` есть почти одинаковая часть
```
 <div className="task-6">
<h3>Task-6</h3>
<h4>Breaking Bad ©</h4>
```
Из этого можно создать компонент вроде "TaskCard", а те значения которые отличаются можно передавать как props

**Comment by rubanykRoman** [comment]
done
