### ISSUE TITLE
Закомментированный код

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [rubanykRoman/test-task-onix-react-internship#4]
<img width="314" alt="Снимок экрана 2021-04-02 в 21 18 40" src="https://user-images.githubusercontent.com/59687966/113442600-00883b80-93f9-11eb-9bdf-c41b048e8b8f.png">

Комментарии нужны чтобы хранить описание функций или сложных частей кода, лучше убрать не нужный код

**Comment by rubanykRoman** [comment]
лишние комменты убрал
